# Generated by Django 3.2.5 on 2022-03-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncaaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballOutsidersFPlusRatings',
            fields=[
                ('Team', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('F_plus', models.FloatField()),
                ('OF_plus', models.FloatField()),
                ('DF_plus', models.FloatField()),
                ('FEI', models.FloatField()),
                ('SP_plus', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teammappings',
            name='fd_team_key',
        ),
        migrations.AlterField(
            model_name='teammappings',
            name='fd_team_id',
            field=models.ForeignKey(blank=True, db_column='fd_team_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fd_team_id', to='ncaaf.fantasydataleaguehierarchy'),
        ),
        migrations.CreateModel(
            name='GameBetCalcs',
            fields=[
                ('game_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ncaaf.fantasydatagames')),
                ('away_elo_pre', models.IntegerField(null=True)),
                ('home_elo_pre', models.IntegerField(null=True)),
                ('away_elo_prob', models.FloatField(null=True)),
                ('home_elo_prob', models.FloatField(null=True)),
                ('away_elo_post', models.IntegerField(null=True)),
                ('home_elo_post', models.IntegerField(null=True)),
                ('home_hfa_elo_adj', models.IntegerField(null=True)),
                ('away_elo_adj', models.IntegerField(null=True)),
                ('home_elo_adj', models.IntegerField(null=True)),
                ('away_scoring_matchup', models.FloatField(null=True)),
                ('home_scoring_matchup', models.FloatField(null=True)),
                ('away_matchup_elo_adj', models.IntegerField(null=True)),
                ('home_matchup_elo_adj', models.IntegerField(null=True)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='ncaaf.fantasydataleaguehierarchy')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='ncaaf.fantasydataleaguehierarchy')),
            ],
        ),
        migrations.AlterField(
            model_name='teammappings',
            name='fo_team',
            field=models.ForeignKey(blank=True, db_column='fo_team', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ncaaf.footballoutsidersfplusratings'),
        ),
    ]
