# Generated by Django 3.2.5 on 2022-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncaaf', '0002_auto_20220401_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmBetCalcs',
            fields=[
                ('cfbd_game_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('away_ml', models.IntegerField(null=True)),
                ('home_ml', models.IntegerField(null=True)),
                ('away_ml_prob', models.FloatField(null=True)),
                ('home_ml_prob', models.FloatField(null=True)),
                ('away_ml_implied_prob', models.FloatField(null=True)),
                ('home_ml_implied_prob', models.FloatField(null=True)),
                ('away_ml_bayes_prob', models.FloatField(null=True)),
                ('home_ml_bayes_prob', models.FloatField(null=True)),
                ('ml_overround', models.FloatField(null=True)),
                ('ml_vig', models.FloatField(null=True)),
                ('away_ml_prob_less_vig', models.FloatField(null=True)),
                ('home_ml_prob_less_vig', models.FloatField(null=True)),
                ('away_ml_er', models.FloatField(null=True)),
                ('home_ml_er', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GameBetCalcs',
            new_name='CeloBetCalcs',
        ),
    ]
